"""
quiz.py — AI-generated knowledge quiz for the JRG Financial Solutions learning platform.

What this does:
- Adds a short (3-question) multiple-choice quiz that tests the user on the
  lesson they currently have open in the Learn tab.
- The questions are *generated by Claude* and grounded in our own lesson content
  (the same LESSON_CONTEXT used by the AI tutor), so the quiz always matches the
  curriculum instead of random general-knowledge trivia.
- Claude returns the quiz as structured JSON, which we parse into a clean
  multiple-choice UI. We grade locally (no second API call), show the score,
  and explain every answer.
- If a user is logged in, their best score is saved to the database via
  upsert_lesson_progress(..., quiz_score=...), reusing the existing schema.

Guardrails: questions stay educational — they test understanding of concepts,
never "what should I buy/sell." The same rules the tutor follows apply here.

The Anthropic API is ONLY called when the user clicks "Generate quiz." It never
fires on its own or on the app's auto-refresh.
"""

import json
import streamlit as st

# Reuse the tutor's model, client factory, and grounded lesson content so the
# quiz and the chat tutor always stay in sync. The hint/explanation helpers are
# what fuse the quiz and the chat into one diagnose-and-explain loop.
from tutor import (
    MODEL, LESSON_CONTEXT, _get_client,
    generate_hint, generate_explanation, build_missed_question_seed,
)

# How many questions each quiz has. Kept small (3) for a quick knowledge check.
NUM_QUESTIONS = 3


# ---------------------------------------------------------------------------
# Fallback quizzes.
#
# If there's no API key (or the API call fails) the app still needs to work —
# especially during a live demo. We keep one hand-written quiz per lesson here,
# keyed by the same lesson id used everywhere else. Claude-generated quizzes are
# preferred; these are only the safety net.
# ---------------------------------------------------------------------------
FALLBACK_QUIZZES = {
    1: [
        {
            "question": "In one sentence, what is the buy-and-hold strategy?",
            "options": [
                "Buy an asset once and hold it until the end of your time horizon.",
                "Trade in and out of stocks based on daily price signals.",
                "Sell everything whenever the market drops 5%.",
                "Rebalance your portfolio every single week.",
            ],
            "correct_index": 0,
            "explanation": (
                "Buy and hold means buying once and doing nothing until you sell at "
                "the end of your horizon — no timing, signals, or rebalancing."
            ),
        },
        {
            "question": "What does CAGR measure?",
            "options": [
                "The single worst day the stock had.",
                "The annualized compound growth rate over the holding period.",
                "How many shares you own.",
                "The total fees you paid your broker.",
            ],
            "correct_index": 1,
            "explanation": (
                "CAGR = (V_end / V_start)^(1/T) - 1. It compresses the whole holding "
                "period into one annualized compound growth number."
            ),
        },
        {
            "question": "Why is max drawdown considered 'the real cost' of buy and hold?",
            "options": [
                "It is a tax you pay every year.",
                "It is the broker commission on each trade.",
                "It is the worst peak-to-trough drop you must endure without selling.",
                "It is the dividend you give up by holding.",
            ],
            "correct_index": 2,
            "explanation": (
                "Max drawdown is the worst peak-to-trough decline. To earn long-run "
                "returns you have to hold through drops of 30–50% without panic-selling."
            ),
        },
    ],
}


def _build_quiz_prompt(lesson_id):
    """
    Build the instruction prompt that asks Claude to write the quiz as JSON.

    We inject the same lesson text the tutor uses, so the questions are grounded
    in our curriculum. The prompt is strict about returning ONLY JSON so we can
    parse it reliably.
    """
    lesson_text = LESSON_CONTEXT.get(lesson_id, "")

    if lesson_text:
        source = (
            "Base every question ONLY on the following lesson content. Do not test "
            "anything the lesson does not cover:\n\n" + lesson_text
        )
    else:
        source = (
            "There is no specific lesson open, so write beginner-level general "
            "investing questions (what a stock is, diversification, risk vs. return, "
            "compounding). Keep them genuinely introductory."
        )

    return (
        "You are the quiz writer for JRG Financial Solutions, a platform that teaches "
        "young adults the basics of investing.\n\n"
        f"Write exactly {NUM_QUESTIONS} multiple-choice questions that test whether the "
        "learner understood the material. Rules:\n"
        "- Each question has exactly 4 options.\n"
        "- Exactly one option is correct.\n"
        "- Questions test conceptual understanding, NOT personalized advice. Never ask "
        "what someone 'should buy/sell' or predict prices.\n"
        "- Keep wording clear and beginner-friendly.\n"
        "- Write a one-sentence explanation for why the correct answer is right.\n\n"
        f"{source}\n\n"
        "Return ONLY a JSON object — no markdown, no backticks, no text before or after. "
        "Use exactly this shape:\n"
        '{\n'
        '  "questions": [\n'
        '    {\n'
        '      "question": "string",\n'
        '      "options": ["string", "string", "string", "string"],\n'
        '      "correct_index": 0,\n'
        '      "explanation": "string"\n'
        '    }\n'
        '  ]\n'
        '}'
    )


def _parse_quiz_json(raw_text):
    """
    Parse the model's response into a validated list of question dicts.

    Returns the list on success, or None if the response is malformed. We strip
    any stray markdown fences first, then validate the structure so a bad
    response can never crash the UI.
    """
    if not raw_text:
        return None

    text = raw_text.strip()
    # Defensive: remove ```json ... ``` fences if the model added them anyway.
    if text.startswith("```"):
        text = text.strip("`")
        # After stripping backticks a leading "json" label may remain.
        if text.lstrip().lower().startswith("json"):
            text = text.lstrip()[4:]

    # If there's surrounding prose, grab the outermost JSON object.
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]

    try:
        data = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None

    questions = data.get("questions") if isinstance(data, dict) else None
    if not isinstance(questions, list) or not questions:
        return None

    cleaned = []
    for q in questions:
        if not isinstance(q, dict):
            return None
        text_q = q.get("question")
        options = q.get("options")
        idx = q.get("correct_index")
        explanation = q.get("explanation", "")
        # Validate each field defensively.
        if not isinstance(text_q, str) or not text_q.strip():
            return None
        if not isinstance(options, list) or len(options) != 4:
            return None
        if not all(isinstance(o, str) and o.strip() for o in options):
            return None
        if not isinstance(idx, int) or not (0 <= idx < 4):
            return None
        cleaned.append({
            "question": text_q.strip(),
            "options": [o.strip() for o in options],
            "correct_index": idx,
            "explanation": (explanation or "").strip(),
        })

    return cleaned or None


def grade_quiz(questions, user_answers):
    """
    Grade a quiz locally — no API call, fully deterministic and testable.

    questions:    list of question dicts (each carrying a 'correct_index').
    user_answers: list of selected option indices aligned by position with
                  `questions`. A None (or missing) entry counts as unanswered
                  and therefore incorrect.

    Returns a summary dict:
        {
          "total": int,
          "correct_count": int,
          "score_percent": int,            # 0..100, rounded
          "results": [                     # one entry per question, in order
            {"index": i, "selected": a, "correct_index": c, "is_correct": bool},
            ...
          ],
        }

    Short or over-long `user_answers` lists are tolerated so a half-finished
    quiz can never crash grading.
    """
    total = len(questions)
    results = []
    correct_count = 0
    for i, q in enumerate(questions):
        selected = user_answers[i] if i < len(user_answers) else None
        correct_index = q.get("correct_index")
        is_correct = selected is not None and selected == correct_index
        if is_correct:
            correct_count += 1
        results.append({
            "index": i,
            "selected": selected,
            "correct_index": correct_index,
            "is_correct": is_correct,
        })
    score_percent = round(100 * correct_count / total) if total else 0
    return {
        "total": total,
        "correct_count": correct_count,
        "score_percent": score_percent,
        "results": results,
    }


def generate_quiz(lesson_id):
    """
    Generate a quiz for the given lesson.

    Tries Claude first (grounded in lesson content). Falls back to a hand-written
    quiz if there's no API key, the library is missing, the call fails, or the
    response can't be parsed. Returns (questions, source) where source is
    "ai" or "fallback", or (None, None) if nothing is available.
    """
    client = _get_client()

    # Only attempt the API if we have a real, usable client.
    if client is not None and client != "no_library":
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=1200,
                messages=[{"role": "user", "content": _build_quiz_prompt(lesson_id)}],
            )
            questions = _parse_quiz_json(response.content[0].text)
            if questions:
                return questions, "ai"
        except Exception:
            # Swallow and fall through to the fallback — never crash the quiz.
            pass

    fallback = FALLBACK_QUIZZES.get(lesson_id)
    if fallback:
        return fallback, "fallback"

    return None, None


def _save_score(lesson_id, score_percent):
    """
    Persist the user's best quiz score to the database, if logged in.

    Uses the existing user_lesson_progress.quiz_score column. We only ever
    upgrade a stored score, never lower it. Fails silently — saving a score
    should never break the quiz UI.
    """
    user_id = st.session_state.get("user_id")
    if not user_id:
        return
    try:
        from database import upsert_lesson_progress, get_lesson_progress

        existing = get_lesson_progress(user_id, lesson_id)
        best = existing.get("quiz_score") if existing else None
        if best is None or score_percent > best:
            upsert_lesson_progress(
                user_id,
                lesson_id,
                status="in_progress",
                quiz_score=float(score_percent),
            )
    except Exception:
        pass


def show_quiz_section(lesson_id=None):
    """
    Render the quiz UI inside the Tutor tab.

    The user clicks a lesson and its quiz appears immediately — one quiz per
    lesson, no separate "generate" step. The list of lessons is built from
    LESSON_CONTEXT, so it grows automatically as lessons are added. The
    `lesson_id` argument is accepted for backward compatibility but unused.
    """
    st.subheader("📝 Quick Quiz")
    st.caption(
        "Pick a lesson to be quizzed on. A short multiple-choice quiz is "
        "generated from that lesson's material."
    )

    available = sorted(LESSON_CONTEXT.keys())
    if not available:
        st.info("No lesson content is available to quiz on yet.")
        return

    titles = {1: "Buy and Hold"}

    # The selected lesson is remembered across reruns. None = nothing picked yet.
    if "quiz_pick" not in st.session_state:
        st.session_state.quiz_pick = None

    st.markdown("**Choose a lesson:**")
    cols = st.columns(len(available))
    for col, lid in zip(cols, available):
        label = titles.get(lid, f"Lesson {lid}")
        # The currently selected lesson renders highlighted (primary).
        is_selected = (st.session_state.quiz_pick == lid)
        with col:
            if st.button(
                label,
                key=f"quiz_pick_btn_{lid}",
                type="primary" if is_selected else "secondary",
            ):
                # Clicking a lesson selects it AND starts its quiz. Switching
                # away from a different lesson clears that one's state first.
                if st.session_state.quiz_pick is not None and st.session_state.quiz_pick != lid:
                    _clear_quiz_state(st.session_state.quiz_pick)
                st.session_state.quiz_pick = lid
                _ensure_quiz_loaded(lid)
                st.rerun()

    picked = st.session_state.quiz_pick
    if picked is None:
        return

    _run_quiz_for_lesson(picked)

def _clear_quiz_state(lesson_id):
    """Wipe a lesson's quiz state so a fresh quiz can start."""
    quiz_key = f"quiz_questions_{lesson_id}"
    n = len(st.session_state.get(quiz_key, []))
    for k in (quiz_key, f"quiz_source_{lesson_id}", f"quiz_submitted_{lesson_id}"):
        st.session_state.pop(k, None)
    for i in range(n):
        st.session_state.pop(f"quiz_ans_{lesson_id}_{i}", None)
        st.session_state.pop(f"quiz_hint_{lesson_id}_{i}", None)


def _run_quiz_for_lesson(lesson_id):
    """
    The quiz flow (generate -> answer -> submit -> score) for one lesson.
    This is the body that used to live in show_quiz_section.
    """
    quiz_key = f"quiz_questions_{lesson_id}"
    source_key = f"quiz_source_{lesson_id}"
    submitted_key = f"quiz_submitted_{lesson_id}"

    # --- Generate ----------------------------------------------------------
    if quiz_key not in st.session_state:
        if st.button("Generate quiz", key=f"gen_quiz_{lesson_id}"):
            with st.spinner("Writing your quiz..."):
                questions, source = generate_quiz(lesson_id)
            if not questions:
                st.warning("No quiz is available for this lesson yet.")
                return
            st.session_state[quiz_key] = questions
            st.session_state[source_key] = source
            st.session_state[submitted_key] = False
            st.rerun()
        return

    questions = st.session_state[quiz_key]
    source = st.session_state.get(source_key, "ai")
    if source == "fallback":
        st.info("Showing a built-in quiz (AI generation was unavailable).")

    # --- Answer ------------------------------------------------------------
    submitted = st.session_state.get(submitted_key, False)
    user_answers = []
    for i, q in enumerate(questions):
        st.markdown(f"**Question {i + 1}. {q['question']}**")
        choice = st.radio(
            "Choose one:",
            options=list(range(len(q["options"]))),
            format_func=lambda idx, opts=q["options"]: opts[idx],
            key=f"quiz_ans_{lesson_id}_{i}",
            index=None,
            disabled=submitted,
        )
        user_answers.append(choice)

        if not submitted:
            # --- Hint: nudge a stuck learner without revealing the answer -----
            hint_key = f"quiz_hint_{lesson_id}_{i}"
            if st.button("💡 Hint", key=f"quiz_hint_btn_{lesson_id}_{i}"):
                with st.spinner("Thinking of a nudge..."):
                    st.session_state[hint_key] = generate_hint(
                        q["question"], lesson_id, options=q["options"]
                    )
            if st.session_state.get(hint_key):
                st.info(st.session_state[hint_key])
        else:
            correct = q["correct_index"]
            if choice == correct:
                st.success(f"Correct — {q['options'][correct]}")
            else:
                picked = q["options"][choice] if choice is not None else "No answer"
                st.error(f"Your answer: {picked}")
                st.markdown(f"Correct answer: **{q['options'][correct]}**")
                # --- Explain more: hand this miss to the chat tutor -----------
                if st.button("🧠 Explain more", key=f"quiz_explain_btn_{lesson_id}_{i}"):
                    _seed_tutor_with_missed_question(lesson_id, q, choice)
                    st.rerun()
            if q["explanation"]:
                st.caption(f"Why: {q['explanation']}")
        st.markdown("")

    # --- Submit / results --------------------------------------------------
    if not submitted:
        if st.button("Submit answers", key=f"submit_quiz_{lesson_id}", type="primary"):
            if any(a is None for a in user_answers):
                st.warning("Please answer all questions before submitting.")
            else:
                st.session_state[submitted_key] = True
                st.rerun()
    else:
        result = grade_quiz(questions, user_answers)
        correct_count = result["correct_count"]
        total = result["total"]
        score_percent = result["score_percent"]
        st.markdown("---")
        st.metric("Your score", f"{correct_count} / {total}  ({score_percent}%)")

        if score_percent == 100:
            st.success("Perfect score — you've got this lesson down.")
        elif score_percent >= 67:
            st.info("Nice work. Review the explanations above to lock it in.")
        else:
            st.warning("Worth another look — reread the lesson, or tap **Explain more** on a miss.")

        _save_score(lesson_id, score_percent)

        if st.button("Try another quiz", key=f"retry_quiz_{lesson_id}"):
            _clear_quiz_state(lesson_id)
            st.rerun()

def _seed_tutor_with_missed_question(lesson_id, question, user_choice):
    """
    Hand a missed quiz question to the chat tutor: this is the bridge that turns
    two separate features into one diagnose-and-explain loop.

    We append a user 'I missed this' turn plus an in-depth assistant explanation
    to the shared tutor conversation, then point the tutor's grounding at this
    lesson so the learner's follow-up questions stay on-topic.
    """
    correct_index = question.get("correct_index")
    options = question.get("options", [])
    correct_answer = options[correct_index] if isinstance(correct_index, int) and 0 <= correct_index < len(options) else "(unknown)"
    user_answer = options[user_choice] if user_choice is not None and 0 <= user_choice < len(options) else "No answer"

    with st.spinner("Bringing this over to the tutor..."):
        explanation = generate_explanation(
            question["question"],
            user_answer,
            correct_answer,
            lesson_id,
            known_explanation=question.get("explanation", ""),
        )

    seed = build_missed_question_seed(question["question"], user_answer, correct_answer)
    if "tutor_messages" not in st.session_state:
        st.session_state.tutor_messages = []
    st.session_state.tutor_messages.append({"role": "user", "content": seed})
    st.session_state.tutor_messages.append({"role": "assistant", "content": explanation})

    # Ground the tutor chat on this lesson and flag the handoff for the UI.
    st.session_state.tutor_lesson = lesson_id
    st.session_state.tutor_just_seeded = True


def _ensure_quiz_loaded(lesson_id):
    """Generate and store the quiz for a lesson if it isn't already loaded."""
    quiz_key = f"quiz_questions_{lesson_id}"
    if quiz_key in st.session_state:
        return
    with st.spinner("Writing your quiz..."):
        questions, source = generate_quiz(lesson_id)
    if questions:
        st.session_state[quiz_key] = questions
        st.session_state[f"quiz_source_{lesson_id}"] = source
        st.session_state[f"quiz_submitted_{lesson_id}"] = False