"""
quiz.py — AI-generated knowledge quiz for the JRG Financial Solutions learning platform.

What this does:
- Adds a short (3-question) multiple-choice quiz that tests the user on the
  lesson they currently have open in the Learn tab.
- The questions are *generated by Claude* and grounded in our own lesson content
  (the same LESSON_CONTEXT used by the AI tutor), so the quiz always matches the
  curriculum instead of random general-knowledge trivia.
- Claude returns the quiz as structured JSON, which we parse into a clean
  multiple-choice UI. We grade locally (no second API call), show the score,
  and explain every answer.
- If a user is logged in, their best score is saved to the database via
  upsert_lesson_progress(..., quiz_score=...), reusing the existing schema.

Guardrails: questions stay educational — they test understanding of concepts,
never "what should I buy/sell." The same rules the tutor follows apply here.

The Anthropic API is ONLY called when the user clicks "Generate quiz." It never
fires on its own or on the app's auto-refresh.
"""

import json
import streamlit as st

# Reuse the tutor's model, client factory, and grounded lesson content so the
# quiz and the chat tutor always stay in sync. The hint/explanation helpers are
# what fuse the quiz and the chat into one diagnose-and-explain loop.
from tutor import (
    MODEL, LESSON_CONTEXT, LESSON_TITLES, _get_client,
    generate_hint, generate_explanation, build_missed_question_seed,
)

# How many questions each quiz has. Kept small (3) for a quick knowledge check.
NUM_QUESTIONS = 3


# ---------------------------------------------------------------------------
# Fallback quizzes.
#
# If there's no API key (or the API call fails) the app still needs to work —
# especially during a live demo. We keep one hand-written quiz per lesson here,
# keyed by the same lesson id used everywhere else. Claude-generated quizzes are
# preferred; these are only the safety net.
# ---------------------------------------------------------------------------
FALLBACK_QUIZZES = {
    1: [
        {
            "question": "In one sentence, what is the buy-and-hold strategy?",
            "concept": "Buy and hold",
            "options": [
                "Buy an asset once and hold it until the end of your time horizon.",
                "Trade in and out of stocks based on daily price signals.",
                "Sell everything whenever the market drops 5%.",
                "Rebalance your portfolio every single week.",
            ],
            "correct_index": 0,
            "explanation": (
                "Buy and hold means buying once and doing nothing until you sell at "
                "the end of your horizon — no timing, signals, or rebalancing."
            ),
        },
        {
            "question": "What does CAGR measure?",
            "concept": "CAGR",
            "options": [
                "The single worst day the stock had.",
                "The annualized compound growth rate over the holding period.",
                "How many shares you own.",
                "The total fees you paid your broker.",
            ],
            "correct_index": 1,
            "explanation": (
                "CAGR = (V_end / V_start)^(1/T) - 1. It compresses the whole holding "
                "period into one annualized compound growth number."
            ),
        },
        {
            "question": "Why is max drawdown considered 'the real cost' of buy and hold?",
            "concept": "Max drawdown",
            "options": [
                "It is a tax you pay every year.",
                "It is the broker commission on each trade.",
                "It is the worst peak-to-trough drop you must endure without selling.",
                "It is the dividend you give up by holding.",
            ],
            "correct_index": 2,
            "explanation": (
                "Max drawdown is the worst peak-to-trough decline. To earn long-run "
                "returns you have to hold through drops of 30–50% without panic-selling."
            ),
        },
    ],
}


def _build_quiz_prompt(lesson_id):
    """
    Build the instruction prompt that asks Claude to write the quiz as JSON.

    We inject the same lesson text the tutor uses, so the questions are grounded
    in our curriculum. The prompt is strict about returning ONLY JSON so we can
    parse it reliably.
    """
    lesson_text = LESSON_CONTEXT.get(lesson_id, "")

    if lesson_text:
        source = (
            "Base every question ONLY on the following lesson content. Do not test "
            "anything the lesson does not cover:\n\n" + lesson_text
        )
    else:
        source = (
            "There is no specific lesson open, so write beginner-level general "
            "investing questions (what a stock is, diversification, risk vs. return, "
            "compounding). Keep them genuinely introductory."
        )

    return (
        "You are the quiz writer for JRG Financial Solutions, a platform that teaches "
        "young adults the basics of investing.\n\n"
        f"Write exactly {NUM_QUESTIONS} multiple-choice questions that test whether the "
        "learner understood the material. Rules:\n"
        "- Each question has exactly 4 options.\n"
        "- Exactly one option is correct.\n"
        "- Questions test conceptual understanding, NOT personalized advice. Never ask "
        "what someone 'should buy/sell' or predict prices.\n"
        "- Keep wording clear and beginner-friendly.\n"
        "- Write a one-sentence explanation for why the correct answer is right.\n"
        "- Tag each question with a short 'concept' (2-4 words) naming the single "
        "idea it tests (e.g. \"CAGR\", \"max drawdown\", \"moving average crossover\"). "
        "Reuse the same wording for the same idea so concepts can be tracked.\n\n"
        f"{source}\n\n"
        "Return ONLY a JSON object — no markdown, no backticks, no text before or after. "
        "Use exactly this shape:\n"
        '{\n'
        '  "questions": [\n'
        '    {\n'
        '      "question": "string",\n'
        '      "options": ["string", "string", "string", "string"],\n'
        '      "correct_index": 0,\n'
        '      "explanation": "string",\n'
        '      "concept": "string"\n'
        '    }\n'
        '  ]\n'
        '}'
    )


def _parse_quiz_json(raw_text):
    """
    Parse the model's response into a validated list of question dicts.

    Returns the list on success, or None if the response is malformed. We strip
    any stray markdown fences first, then validate the structure so a bad
    response can never crash the UI.
    """
    if not raw_text:
        return None

    text = raw_text.strip()
    # Defensive: remove ```json ... ``` fences if the model added them anyway.
    if text.startswith("```"):
        text = text.strip("`")
        # After stripping backticks a leading "json" label may remain.
        if text.lstrip().lower().startswith("json"):
            text = text.lstrip()[4:]

    # If there's surrounding prose, grab the outermost JSON object.
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]

    try:
        data = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None

    questions = data.get("questions") if isinstance(data, dict) else None
    if not isinstance(questions, list) or not questions:
        return None

    cleaned = []
    for q in questions:
        if not isinstance(q, dict):
            return None
        text_q = q.get("question")
        options = q.get("options")
        idx = q.get("correct_index")
        explanation = q.get("explanation", "")
        concept = q.get("concept", "")
        # Validate each field defensively.
        if not isinstance(text_q, str) or not text_q.strip():
            return None
        if not isinstance(options, list) or len(options) != 4:
            return None
        if not all(isinstance(o, str) and o.strip() for o in options):
            return None
        if not isinstance(idx, int) or not (0 <= idx < 4):
            return None
        cleaned.append({
            "question": text_q.strip(),
            "options": [o.strip() for o in options],
            "correct_index": idx,
            "explanation": (explanation or "").strip(),
            "concept": (concept or "General").strip() or "General",
        })

    return cleaned or None


def grade_quiz(questions, user_answers):
    """
    Grade a quiz locally — no API call, fully deterministic and testable.

    questions:    list of question dicts (each carrying a 'correct_index').
    user_answers: list of selected option indices aligned by position with
                  `questions`. A None (or missing) entry counts as unanswered
                  and therefore incorrect.

    Returns a summary dict:
        {
          "total": int,
          "correct_count": int,
          "score_percent": int,            # 0..100, rounded
          "results": [                     # one entry per question, in order
            {"index": i, "selected": a, "correct_index": c, "is_correct": bool},
            ...
          ],
        }

    Short or over-long `user_answers` lists are tolerated so a half-finished
    quiz can never crash grading.
    """
    total = len(questions)
    results = []
    correct_count = 0
    for i, q in enumerate(questions):
        selected = user_answers[i] if i < len(user_answers) else None
        correct_index = q.get("correct_index")
        is_correct = selected is not None and selected == correct_index
        if is_correct:
            correct_count += 1
        results.append({
            "index": i,
            "selected": selected,
            "correct_index": correct_index,
            "is_correct": is_correct,
        })
    score_percent = round(100 * correct_count / total) if total else 0
    return {
        "total": total,
        "correct_count": correct_count,
        "score_percent": score_percent,
        "results": results,
    }


def generate_quiz(lesson_id):
    """
    Generate a quiz for the given lesson.

    Tries Claude first (grounded in lesson content). Falls back to a hand-written
    quiz if there's no API key, the library is missing, the call fails, or the
    response can't be parsed. Returns (questions, source) where source is
    "ai" or "fallback", or (None, None) if nothing is available.
    """
    client = _get_client()

    # Only attempt the API if we have a real, usable client.
    if client is not None and client != "no_library":
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=1200,
                messages=[{"role": "user", "content": _build_quiz_prompt(lesson_id)}],
            )
            questions = _parse_quiz_json(response.content[0].text)
            if questions:
                return questions, "ai"
        except Exception:
            # Swallow and fall through to the fallback — never crash the quiz.
            pass

    fallback = FALLBACK_QUIZZES.get(lesson_id)
    if fallback:
        return fallback, "fallback"

    return None, None


def _build_review_prompt(weak_concepts):
    """
    Build a prompt that asks Claude for questions targeting the user's weak
    concepts. `weak_concepts` is a list of concept-stat dicts (worst first);
    we pass their labels so the review is grounded in what the learner keeps
    missing, and reuse any lesson content we have for extra grounding.
    """
    labels = [c["concept"] for c in weak_concepts]
    concept_list = ", ".join(f'"{c}"' for c in labels)

    # Ground on whatever lesson content we have available (best-effort).
    grounding = "\n\n".join(
        text for text in (LESSON_CONTEXT.get(k, "") for k in sorted(LESSON_CONTEXT)) if text
    )
    grounding_block = (
        "Where relevant, ground the questions in this lesson material:\n\n" + grounding
        if grounding else ""
    )

    return (
        "You are the quiz writer for JRG Financial Solutions. The learner has been "
        "getting these concepts wrong and needs targeted review:\n"
        f"{concept_list}\n\n"
        f"Write exactly {NUM_QUESTIONS} multiple-choice questions that focus on those "
        "weak concepts (weight toward the earlier ones, which are the weakest). Rules:\n"
        "- Each question has exactly 4 options, exactly one correct.\n"
        "- Test conceptual understanding, never 'what should I buy/sell' or price predictions.\n"
        "- Tag each question's 'concept' with the exact weak-concept label it targets, "
        "chosen from the list above, so mastery can be tracked.\n"
        "- Give a one-sentence explanation for the correct answer.\n\n"
        f"{grounding_block}\n\n"
        "Return ONLY a JSON object — no markdown or backticks — of this shape:\n"
        '{ "questions": [ { "question": "string", "options": ["string","string","string","string"], '
        '"correct_index": 0, "explanation": "string", "concept": "string" } ] }'
    )


def _review_fallback(weak_concepts):
    """
    Offline fallback for the review quiz: pull hand-written questions whose
    concept matches one of the user's weak concepts. Keeps the review usable
    with no API key (e.g. during a live demo). Returns a question list or None.
    """
    weak_labels = {c["concept"].lower() for c in weak_concepts}
    pool = []
    for questions in FALLBACK_QUIZZES.values():
        for q in questions:
            if (q.get("concept", "").lower() in weak_labels) and q not in pool:
                pool.append(q)
    return pool[:NUM_QUESTIONS] or None


def generate_review_quiz(user_id):
    """
    Generate a review quiz weighted toward a user's weakest concepts.

    Returns (questions, source, weak_concepts). If the user has no tracked weak
    concepts yet, returns (None, None, []). Tries Claude first (grounded in the
    weak-concept labels), then falls back to matching hand-written questions.
    """
    from database import get_weak_concepts

    weak = get_weak_concepts(user_id, limit=5)
    if not weak:
        return None, None, []

    client = _get_client()
    if client is not None and client != "no_library":
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=1200,
                messages=[{"role": "user", "content": _build_review_prompt(weak)}],
            )
            questions = _parse_quiz_json(response.content[0].text)
            if questions:
                return questions, "ai", weak
        except Exception:
            pass

    fallback = _review_fallback(weak)
    if fallback:
        return fallback, "fallback", weak

    return None, None, weak


def _save_score(lesson_id, score_percent):
    """
    Advance the user's lesson progress after a quiz, if logged in.

    The shipped schema tracks lesson status ('not_started' / 'in_progress' /
    'completed'), so a perfect quiz marks the lesson completed and any other
    score marks it in-progress. Fails silently — saving progress should never
    break the quiz UI.
    """
    user_id = st.session_state.get("user_id")
    if not user_id:
        return
    try:
        from database import update_lesson_progress

        status = "completed" if score_percent >= 100 else "in_progress"
        update_lesson_progress(user_id, lesson_id, status)
    except Exception:
        pass


def _record_concept_results(questions, user_answers, lesson_id=None):
    """
    Feed each graded answer into the adaptive concept tracker.

    For every question we look up its concept tag and record whether the user
    got it right, which updates that concept's miss count and correct-streak in
    the database. This is what lets the review quiz target weak spots and retire
    mastered concepts. No-ops if the user isn't logged in.
    """
    user_id = st.session_state.get("user_id")
    if not user_id:
        return
    try:
        from database import record_quiz_result

        for i, q in enumerate(questions):
            concept = (q.get("concept") or "General").strip() or "General"
            selected = user_answers[i] if i < len(user_answers) else None
            is_correct = selected is not None and selected == q.get("correct_index")
            record_quiz_result(user_id, concept, is_correct, lesson_id=lesson_id)
    except Exception:
        pass


def show_quiz_section(lesson_id=None):
    """
    Render the quiz UI inside the Tutor tab.

    The user clicks a lesson and its quiz appears immediately — one quiz per
    lesson, no separate "generate" step. The list of lessons is built from
    LESSON_CONTEXT, so it grows automatically as lessons are added. The
    `lesson_id` argument is accepted for backward compatibility but unused.
    """
    st.subheader("📝 Quick Quiz")

    user_id = st.session_state.get("user_id")
    mode = st.radio(
        "Quiz mode",
        options=["By lesson", "🎯 Review weak spots"],
        horizontal=True,
        key="quiz_mode",
        label_visibility="collapsed",
    )

    # Review mode: adaptive quiz weighted toward the concepts this user keeps
    # missing. Falls back to a friendly message when there's nothing to review.
    if mode == "🎯 Review weak spots":
        _run_review_quiz(user_id)
        return

    st.caption(
        "Pick a lesson to be quizzed on. A short multiple-choice quiz is "
        "generated from that lesson's material."
    )

    available = sorted(LESSON_CONTEXT.keys())
    if not available:
        st.info("No lesson content is available to quiz on yet.")
        return

    titles = LESSON_TITLES

    # The selected lesson is remembered across reruns. None = nothing picked yet.
    if "quiz_pick" not in st.session_state:
        st.session_state.quiz_pick = None

    st.markdown("**Choose a lesson:**")
    # Lay the lesson buttons out in rows of five so all ten fit comfortably.
    per_row = 5
    for row_start in range(0, len(available), per_row):
        row = available[row_start:row_start + per_row]
        cols = st.columns(per_row)
        for col, lid in zip(cols, row):
            label = titles.get(lid, f"Lesson {lid}")
            # The currently selected lesson renders highlighted (primary).
            is_selected = (st.session_state.quiz_pick == lid)
            with col:
                if st.button(
                    label,
                    key=f"quiz_pick_btn_{lid}",
                    type="primary" if is_selected else "secondary",
                    use_container_width=True,
                ):
                    # Clicking a lesson selects it AND starts its quiz. Switching
                    # away from a different lesson clears that one's state first.
                    if st.session_state.quiz_pick is not None and st.session_state.quiz_pick != lid:
                        _clear_quiz_state(st.session_state.quiz_pick)
                    st.session_state.quiz_pick = lid
                    _ensure_quiz_loaded(lid)
                    st.rerun()

    picked = st.session_state.quiz_pick
    if picked is None:
        return

    _run_quiz_for_lesson(picked)

def _run_review_quiz(user_id):
    """
    Adaptive review-quiz flow: show the user's weakest concepts, generate a quiz
    weighted toward them, then answer -> submit -> score. Every answer is
    recorded, so concepts get retired from the review list once mastered.
    """
    if not user_id:
        st.info("Log in to build a personalized review from the concepts you miss.")
        return

    from database import get_weak_concepts

    weak = get_weak_concepts(user_id, limit=5)
    if not weak:
        st.success(
            "No weak spots tracked yet — take a few lesson quizzes and anything "
            "you miss will show up here for targeted review."
        )
        return

    st.markdown("**Your weakest concepts right now:**")
    st.write(" · ".join(f"{c['concept']} (missed {c['times_missed']}×)" for c in weak))

    quiz_key = "quiz_questions_review"
    source_key = "quiz_source_review"
    submitted_key = "quiz_submitted_review"

    # --- Generate ----------------------------------------------------------
    if quiz_key not in st.session_state:
        if st.button("Generate review quiz", key="gen_quiz_review", type="primary"):
            with st.spinner("Building a review from your weak spots..."):
                questions, source, _ = generate_review_quiz(user_id)
            if not questions:
                st.warning("Couldn't build a review quiz right now — try again in a moment.")
                return
            st.session_state[quiz_key] = questions
            st.session_state[source_key] = source
            st.session_state[submitted_key] = False
            st.rerun()
        return

    questions = st.session_state[quiz_key]
    source = st.session_state.get(source_key, "ai")
    if source == "fallback":
        st.info("Showing built-in review questions (AI generation was unavailable).")

    # --- Answer ------------------------------------------------------------
    submitted = st.session_state.get(submitted_key, False)
    user_answers = []
    for i, q in enumerate(questions):
        st.markdown(f"**Question {i + 1}. {q['question']}**")
        st.caption(f"Concept: {q.get('concept', 'General')}")
        choice = st.radio(
            "Choose one:",
            options=list(range(len(q["options"]))),
            format_func=lambda idx, opts=q["options"]: opts[idx],
            key=f"quiz_ans_review_{i}",
            index=None,
            disabled=submitted,
        )
        user_answers.append(choice)
        if submitted:
            correct = q["correct_index"]
            if choice == correct:
                st.success(f"Correct — {q['options'][correct]}")
            else:
                picked = q["options"][choice] if choice is not None else "No answer"
                st.error(f"Your answer: {picked}")
                st.markdown(f"Correct answer: **{q['options'][correct]}**")
            if q["explanation"]:
                st.caption(f"Why: {q['explanation']}")
        st.markdown("")

    # --- Submit / results --------------------------------------------------
    if not submitted:
        if st.button("Submit answers", key="submit_quiz_review", type="primary"):
            if any(a is None for a in user_answers):
                st.warning("Please answer all questions before submitting.")
            else:
                _record_concept_results(questions, user_answers, lesson_id=None)
                st.session_state[submitted_key] = True
                st.rerun()
    else:
        result = grade_quiz(questions, user_answers)
        st.markdown("---")
        st.metric(
            "Your score",
            f"{result['correct_count']} / {result['total']}  ({result['score_percent']}%)",
        )
        st.caption(
            "Concepts you answer correctly twice in a row are retired from your review list."
        )
        if st.button("New review quiz", key="retry_quiz_review"):
            stale = [quiz_key, source_key, submitted_key] + [
                f"quiz_ans_review_{i}" for i in range(len(questions))
            ]
            for k in stale:
                st.session_state.pop(k, None)
            st.rerun()


def _clear_quiz_state(lesson_id):
    """Wipe a lesson's quiz state so a fresh quiz can start."""
    quiz_key = f"quiz_questions_{lesson_id}"
    n = len(st.session_state.get(quiz_key, []))
    for k in (quiz_key, f"quiz_source_{lesson_id}", f"quiz_submitted_{lesson_id}"):
        st.session_state.pop(k, None)
    for i in range(n):
        st.session_state.pop(f"quiz_ans_{lesson_id}_{i}", None)
        st.session_state.pop(f"quiz_hint_{lesson_id}_{i}", None)


def _run_quiz_for_lesson(lesson_id):
    """
    The quiz flow (generate -> answer -> submit -> score) for one lesson.
    This is the body that used to live in show_quiz_section.
    """
    quiz_key = f"quiz_questions_{lesson_id}"
    source_key = f"quiz_source_{lesson_id}"
    submitted_key = f"quiz_submitted_{lesson_id}"

    # --- Generate ----------------------------------------------------------
    if quiz_key not in st.session_state:
        if st.button("Generate quiz", key=f"gen_quiz_{lesson_id}"):
            with st.spinner("Writing your quiz..."):
                questions, source = generate_quiz(lesson_id)
            if not questions:
                st.warning("No quiz is available for this lesson yet.")
                return
            st.session_state[quiz_key] = questions
            st.session_state[source_key] = source
            st.session_state[submitted_key] = False
            st.rerun()
        return

    questions = st.session_state[quiz_key]
    source = st.session_state.get(source_key, "ai")
    if source == "fallback":
        st.info("Showing a built-in quiz (AI generation was unavailable).")

    # --- Answer ------------------------------------------------------------
    submitted = st.session_state.get(submitted_key, False)
    user_answers = []
    for i, q in enumerate(questions):
        st.markdown(f"**Question {i + 1}. {q['question']}**")
        choice = st.radio(
            "Choose one:",
            options=list(range(len(q["options"]))),
            format_func=lambda idx, opts=q["options"]: opts[idx],
            key=f"quiz_ans_{lesson_id}_{i}",
            index=None,
            disabled=submitted,
        )
        user_answers.append(choice)

        if not submitted:
            # --- Hint: nudge a stuck learner without revealing the answer -----
            hint_key = f"quiz_hint_{lesson_id}_{i}"
            if st.button("💡 Hint", key=f"quiz_hint_btn_{lesson_id}_{i}"):
                with st.spinner("Thinking of a nudge..."):
                    st.session_state[hint_key] = generate_hint(
                        q["question"], lesson_id, options=q["options"]
                    )
            if st.session_state.get(hint_key):
                st.info(st.session_state[hint_key])
        else:
            correct = q["correct_index"]
            if choice == correct:
                st.success(f"Correct — {q['options'][correct]}")
            else:
                picked = q["options"][choice] if choice is not None else "No answer"
                st.error(f"Your answer: {picked}")
                st.markdown(f"Correct answer: **{q['options'][correct]}**")
                # --- Explain more: hand this miss to the chat tutor -----------
                if st.button("🧠 Explain more", key=f"quiz_explain_btn_{lesson_id}_{i}"):
                    _seed_tutor_with_missed_question(lesson_id, q, choice)
                    st.rerun()
            if q["explanation"]:
                st.caption(f"Why: {q['explanation']}")
        st.markdown("")

    # --- Submit / results --------------------------------------------------
    if not submitted:
        if st.button("Submit answers", key=f"submit_quiz_{lesson_id}", type="primary"):
            if any(a is None for a in user_answers):
                st.warning("Please answer all questions before submitting.")
            else:
                _record_concept_results(questions, user_answers, lesson_id=lesson_id)
                st.session_state[submitted_key] = True
                st.rerun()
    else:
        result = grade_quiz(questions, user_answers)
        correct_count = result["correct_count"]
        total = result["total"]
        score_percent = result["score_percent"]
        st.markdown("---")
        st.metric("Your score", f"{correct_count} / {total}  ({score_percent}%)")

        if score_percent == 100:
            st.success("Perfect score — you've got this lesson down.")
        elif score_percent >= 67:
            st.info("Nice work. Review the explanations above to lock it in.")
        else:
            st.warning("Worth another look — reread the lesson, or tap **Explain more** on a miss.")

        _save_score(lesson_id, score_percent)

        if st.button("Try another quiz", key=f"retry_quiz_{lesson_id}"):
            _clear_quiz_state(lesson_id)
            st.rerun()

def _seed_tutor_with_missed_question(lesson_id, question, user_choice):
    """
    Hand a missed quiz question to the chat tutor: this is the bridge that turns
    two separate features into one diagnose-and-explain loop.

    We append a user 'I missed this' turn plus an in-depth assistant explanation
    to the shared tutor conversation, then point the tutor's grounding at this
    lesson so the learner's follow-up questions stay on-topic.
    """
    correct_index = question.get("correct_index")
    options = question.get("options", [])
    correct_answer = options[correct_index] if isinstance(correct_index, int) and 0 <= correct_index < len(options) else "(unknown)"
    user_answer = options[user_choice] if user_choice is not None and 0 <= user_choice < len(options) else "No answer"

    with st.spinner("Bringing this over to the tutor..."):
        explanation = generate_explanation(
            question["question"],
            user_answer,
            correct_answer,
            lesson_id,
            known_explanation=question.get("explanation", ""),
        )

    seed = build_missed_question_seed(question["question"], user_answer, correct_answer)
    if "tutor_messages" not in st.session_state:
        st.session_state.tutor_messages = []
    st.session_state.tutor_messages.append({"role": "user", "content": seed})
    st.session_state.tutor_messages.append({"role": "assistant", "content": explanation})

    # Ground the tutor chat on this lesson and flag the handoff for the UI.
    st.session_state.tutor_lesson = lesson_id
    st.session_state.tutor_just_seeded = True


def _ensure_quiz_loaded(lesson_id):
    """Generate and store the quiz for a lesson if it isn't already loaded."""
    quiz_key = f"quiz_questions_{lesson_id}"
    if quiz_key in st.session_state:
        return
    with st.spinner("Writing your quiz..."):
        questions, source = generate_quiz(lesson_id)
    if questions:
        st.session_state[quiz_key] = questions
        st.session_state[f"quiz_source_{lesson_id}"] = source
        st.session_state[f"quiz_submitted_{lesson_id}"] = False